# Generated by Django 4.1.2 on 2023-08-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('abstract', models.TextField()),
                ('terms', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('ids', models.CharField(max_length=20)),
            ],
        ),
    ]
