# Generated by Django 4.1.2 on 2023-08-11 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0002_recentpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpaper',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
